/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package nsg.portafolio.formulario;

import java.util.List;
import javax.swing.JOptionPane;
import nsg.portafolio.Utiles;
import nsg.portafolio.dao.ConfiguracionDAO;
import nsg.portafolio.model.Configuracion;
import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;

/**
 *
 * @author Acer
 */
public class ConfiguracionFrm extends javax.swing.JFrame {

    private static final Logger log = LogManager.getLogger(ConfiguracionFrm.class);

    /**
     * Creates new form ConfiguracionFrm
     */
    public ConfiguracionFrm() {
        initComponents();
        setLocationRelativeTo(null);

        actualizarLista();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldPom = new javax.swing.JTextField();
        jTextFieldBuild = new javax.swing.JTextField();
        jTextFieldWar = new javax.swing.JTextField();
        jTextFieldWildfly = new javax.swing.JTextField();
        jTextFieldMaven = new javax.swing.JTextField();
        jButtonGuardar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jComboBoxConfiguraciones = new javax.swing.JComboBox<Configuracion>();
        jLabel9 = new javax.swing.JLabel();
        jTextFieldProyecto = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jButtonEliminar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Configuración");
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setText("Directorio de pom.xml (*):");

        jLabel5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel5.setText("Directorio de compilacion (*):");

        jTextFieldPom.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jTextFieldPom.setToolTipText("");
        jTextFieldPom.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        jTextFieldBuild.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        jTextFieldWar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        jTextFieldWildfly.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        jTextFieldMaven.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jTextFieldMaven.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldMavenActionPerformed(evt);
            }
        });

        jButtonGuardar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButtonGuardar.setText("GUARDAR");
        jButtonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGuardarActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Copyright @Norio 2025");

        jLabel7.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Todos los derechos reservados");

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setText("Nombre de WAR (*):");

        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel3.setText("Deployments de Wildfly (*):");

        jLabel4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel4.setText("Directorio de Maven  (*):");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Crear/Modificar Configuración");

        jComboBoxConfiguraciones.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxConfiguracionesItemStateChanged(evt);
            }
        });
        jComboBoxConfiguraciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxConfiguracionesActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel9.setText("Configuración:");

        jTextFieldProyecto.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jTextFieldProyecto.setToolTipText("");
        jTextFieldProyecto.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        jLabel10.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel10.setText("Nombre Proyecto (*):");

        jButtonEliminar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButtonEliminar.setText("ELIMINAR");
        jButtonEliminar.setEnabled(false);
        jButtonEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldProyecto))
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldPom)
                            .addComponent(jTextFieldWildfly)
                            .addComponent(jTextFieldWar)
                            .addComponent(jTextFieldBuild)
                            .addComponent(jTextFieldMaven)
                            .addComponent(jComboBoxConfiguraciones, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jButtonGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                        .addComponent(jButtonEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)))
                .addGap(14, 14, 14)
                .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 1, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBoxConfiguraciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jTextFieldProyecto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldPom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jTextFieldBuild, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldWar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextFieldMaven, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldWildfly, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonGuardar)
                    .addComponent(jButtonEliminar))
                .addGap(18, 18, 18)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldMavenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldMavenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldMavenActionPerformed

    private void jButtonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGuardarActionPerformed

        Configuracion seleccion = (Configuracion) jComboBoxConfiguraciones.getSelectedItem();

        // <editor-fold defaultstate="collapsed" desc="Validación"> 
        if (jTextFieldProyecto.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Nombre Proyecto es obligatorio!",
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
            return;
        } else if (jTextFieldPom.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Directorio de pom.xml es obligatorio!",
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
            return;
        } else if (jTextFieldBuild.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Directorio de compilacion es obligatorio!",
                    "Error",
                    JOptionPane.ERROR_MESSAGE);

            return;
        } else if (jTextFieldWar.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Nombre de WAR es obligatorio!",
                    "Error",
                    JOptionPane.ERROR_MESSAGE);

            return;
        } else if (jTextFieldWildfly.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Directorio de Maven es obligatorio!",
                    "Error",
                    JOptionPane.ERROR_MESSAGE);

            return;
        } else if (jTextFieldMaven.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Deployments de Wildfly es obligatorio!",
                    "Error",
                    JOptionPane.ERROR_MESSAGE);

            return;
        } else if (seleccion == null) {
            JOptionPane.showMessageDialog(null, "Seleccione una configuración",
                    "Error",
                    JOptionPane.ERROR_MESSAGE);

            return;
        }
        // </editor-fold>  

        try {
            jButtonGuardar.setText("GUARDANDO...");
            Utiles.componentesBlocking(jPanel1, true);

            Configuracion conf = Configuracion.builder()
                    .configuracion_id(seleccion.getConfiguracion_id())
                    .nombre_proyecto(jTextFieldProyecto.getText())
                    .pomDir(jTextFieldPom.getText())
                    .buildDir(jTextFieldBuild.getText())
                    .warName(jTextFieldWar.getText())
                    .wildflyDeployDir(jTextFieldWildfly.getText())
                    .mavenExecutable(jTextFieldMaven.getText())
                    .build();

            ConfiguracionDAO confDAO = new ConfiguracionDAO();
            confDAO.guardar(conf);

            JOptionPane.showMessageDialog(null, "Configuración Guardado con éxito",
                    "Status",
                    JOptionPane.INFORMATION_MESSAGE);
            log.info("Configuración creado con exito: " + conf.toString());

            setearCampos();

            jComboBoxConfiguraciones.setSelectedItem(Configuracion.builder().configuracion_id(null).build());

            actualizarLista();
        } catch (Exception ex) {
            ex.printStackTrace();
            log.info("Error: " + ex);
            JOptionPane.showMessageDialog(null, "Error al crear. " + ex,
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
        } finally {
            Utiles.componentesBlocking(jPanel1, false);
            jButtonGuardar.setText("GUARDAR");
        }

    }//GEN-LAST:event_jButtonGuardarActionPerformed

    private void jComboBoxConfiguracionesItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxConfiguracionesItemStateChanged
        // TODO add your handling code here:

    }//GEN-LAST:event_jComboBoxConfiguracionesItemStateChanged

    private void jComboBoxConfiguracionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxConfiguracionesActionPerformed
        // TODO add your handling code here:

        Configuracion seleccion = (Configuracion) jComboBoxConfiguraciones.getSelectedItem();
        if (seleccion != null) {
            log.info("ID: " + seleccion.getConfiguracion_id() + ", Proyecto: " + seleccion.getNombre_proyecto());

            if (seleccion.getConfiguracion_id() == null) {
                setearCampos();
            } else {
                jTextFieldProyecto.setText(seleccion.getNombre_proyecto());

                jTextFieldPom.setText(seleccion.getPomDir());
                jTextFieldBuild.setText(seleccion.getBuildDir());
                jTextFieldWar.setText(seleccion.getWarName());
                jTextFieldWildfly.setText(seleccion.getWildflyDeployDir());
                jTextFieldMaven.setText(seleccion.getMavenExecutable());

            }
        }
    }//GEN-LAST:event_jComboBoxConfiguracionesActionPerformed

    private void jButtonEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEliminarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonEliminarActionPerformed

    private void setearCampos() {
        log.info("Setear Campos");
        jTextFieldProyecto.setText("");
        jTextFieldPom.setText("");
        jTextFieldBuild.setText("");
        jTextFieldWar.setText("");
        jTextFieldWildfly.setText("");
        jTextFieldMaven.setText("");

    }

    private void actualizarLista() {
        log.info("Actualizar la lista de configuracion");
        // Crear lista de configuaraciones
        ConfiguracionDAO cDao = new ConfiguracionDAO();
        try {
            List<Configuracion> lista = cDao.listarTodas();

            log.info("Cantiad de Configuraciones " + lista.size());

            jComboBoxConfiguraciones.removeAllItems();

            jComboBoxConfiguraciones.addItem(Configuracion.builder().nombre_proyecto("Nuevo").build());

            lista.forEach(item -> {
                jComboBoxConfiguraciones.addItem(item);
            });

        } catch (Exception ex) {
            ex.printStackTrace();
            log.info("Error buscar lista de configuarciones. " + ex);
            JOptionPane.showMessageDialog(null, "Error buscar lista de configuarciones. " + ex,
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Configuracion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Configuracion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Configuracion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Configuracion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConfiguracionFrm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonEliminar;
    private javax.swing.JButton jButtonGuardar;
    private javax.swing.JComboBox<Configuracion> jComboBoxConfiguraciones;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextFieldBuild;
    private javax.swing.JTextField jTextFieldMaven;
    private javax.swing.JTextField jTextFieldPom;
    private javax.swing.JTextField jTextFieldProyecto;
    private javax.swing.JTextField jTextFieldWar;
    private javax.swing.JTextField jTextFieldWildfly;
    // End of variables declaration//GEN-END:variables
}
