/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package nsg.portafolio.formulario;

import java.util.List;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import nsg.portafolio.Utiles;
import nsg.portafolio.controller.EjecutarController;
import nsg.portafolio.dao.ConfiguracionDAO;
import nsg.portafolio.model.Configuracion;
import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;

/**
 *
 * @author Acer
 */
public class EjecutarFrm extends javax.swing.JFrame {

    private static final Logger log = LogManager.getLogger(EjecutarFrm.class);

    private String pomDir = "";
    private String buildDir = "";
    private String warName = "";
    private String wildflyDeployDir = "";
    private String mavenExecutable = "";

    /**
     * Creates new form PrincipalFrm
     */
    public EjecutarFrm() {
        initComponents();
        setLocationRelativeTo(null); 

        jTextFieldPom.setText(pomDir);
        jTextFieldBuild.setText(buildDir);
        jTextFieldWar.setText(warName);
        jTextFieldWildfly.setText(wildflyDeployDir);
        jTextFieldMaven.setText(mavenExecutable);

        actualizarLista();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldPom = new javax.swing.JTextField();
        jTextFieldBuild = new javax.swing.JTextField();
        jTextFieldWar = new javax.swing.JTextField();
        jTextFieldWildfly = new javax.swing.JTextField();
        jTextFieldMaven = new javax.swing.JTextField();
        jButtonProcesar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jComboBoxConfiguraciones = new javax.swing.JComboBox<Configuracion>();
        jLabel9 = new javax.swing.JLabel();
        jTextFieldProyecto = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jButtonCerrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Ejecutar");
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setText("Directorio de pom.xml:");

        jLabel5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel5.setText("Directorio de compilacion:");

        jTextFieldPom.setEditable(false);
        jTextFieldPom.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jTextFieldPom.setToolTipText("");
        jTextFieldPom.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        jTextFieldBuild.setEditable(false);
        jTextFieldBuild.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        jTextFieldWar.setEditable(false);
        jTextFieldWar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        jTextFieldWildfly.setEditable(false);
        jTextFieldWildfly.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        jTextFieldMaven.setEditable(false);
        jTextFieldMaven.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jTextFieldMaven.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldMavenActionPerformed(evt);
            }
        });

        jButtonProcesar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButtonProcesar.setText("PROCESAR");
        jButtonProcesar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonProcesarActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Copyright @Norio 2025");

        jLabel7.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Todos los derechos reservados");

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setText("Nombre de WAR:");

        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel3.setText("Deployments de Wildfly:");

        jLabel4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel4.setText("Directorio de Maven:");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Compilar y Deployar WAR en Widlfly");

        jComboBoxConfiguraciones.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxConfiguracionesItemStateChanged(evt);
            }
        });
        jComboBoxConfiguraciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxConfiguracionesActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel9.setText("Configuración:");

        jTextFieldProyecto.setEditable(false);
        jTextFieldProyecto.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jTextFieldProyecto.setToolTipText("");
        jTextFieldProyecto.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        jLabel10.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel10.setText("Nombre Proyecto (*):");

        jButtonCerrar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButtonCerrar.setText("CERRAR");
        jButtonCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCerrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldProyecto)
                            .addComponent(jComboBoxConfiguraciones, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 635, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldPom)
                            .addComponent(jTextFieldWildfly)
                            .addComponent(jTextFieldWar)
                            .addComponent(jTextFieldBuild)
                            .addComponent(jTextFieldMaven)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButtonProcesar, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButtonCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(14, 14, 14)
                .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 5, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBoxConfiguraciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(jTextFieldProyecto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldPom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jTextFieldBuild, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldWar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextFieldMaven, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldWildfly, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonProcesar)
                    .addComponent(jButtonCerrar))
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonProcesarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonProcesarActionPerformed

        Configuracion seleccion = (Configuracion) jComboBoxConfiguraciones.getSelectedItem();

        // <editor-fold defaultstate="collapsed" desc="Validación"> 
        if (jTextFieldProyecto.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Nombre Proyecto es obligatorio!",
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
            return;
        } else if (jTextFieldPom.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Directorio de pom.xml es obligatorio!",
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
            return;
        } else if (jTextFieldBuild.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Directorio de compilacion es obligatorio!",
                    "Error",
                    JOptionPane.ERROR_MESSAGE);

            return;
        } else if (jTextFieldWar.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Nombre de WAR es obligatorio!",
                    "Error",
                    JOptionPane.ERROR_MESSAGE);

            return;
        } else if (jTextFieldWildfly.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Directorio de Maven es obligatorio!",
                    "Error",
                    JOptionPane.ERROR_MESSAGE);

            return;
        } else if (jTextFieldMaven.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Deployments de Wildfly es obligatorio!",
                    "Error",
                    JOptionPane.ERROR_MESSAGE);

            return;
        } else if (seleccion == null) {
            JOptionPane.showMessageDialog(null, "Seleccione una configuración",
                    "Error",
                    JOptionPane.ERROR_MESSAGE);

            return;
        }
        // </editor-fold>  

        pomDir = jTextFieldPom.getText();
        buildDir = jTextFieldBuild.getText();
        warName = jTextFieldWar.getText();
        wildflyDeployDir = jTextFieldWildfly.getText();
        mavenExecutable = jTextFieldMaven.getText();

        Thread hilo = new Thread() {
            @Override
            public void run() {
                Utiles.componentesBlocking(jPanel1, true);
                jButtonProcesar.setText("PROCESANDO...");

                try {

                    EjecutarController inciar = new EjecutarController(pomDir, buildDir, warName, wildflyDeployDir, mavenExecutable);

                    inciar.procesar();

                    JOptionPane.showMessageDialog(null, "Finalizado",
                            "Status",
                            JOptionPane.INFORMATION_MESSAGE);
                } catch (Exception ex) {
                    ex.printStackTrace();
                    JOptionPane.showMessageDialog(null, "Error al procesar. " + ex,
                            "Error",
                            JOptionPane.ERROR_MESSAGE);
                } finally {
                    Utiles.componentesBlocking(jPanel1, false);
                    jButtonProcesar.setText("PROCESAR...");
                }

                log.info("Proceso finalizado. ");

            }
        };
        hilo.start();


    }//GEN-LAST:event_jButtonProcesarActionPerformed


    private void jTextFieldMavenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldMavenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldMavenActionPerformed

    private void jComboBoxConfiguracionesItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxConfiguracionesItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxConfiguracionesItemStateChanged

    private void jComboBoxConfiguracionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxConfiguracionesActionPerformed
        // TODO add your handling code here:

        Configuracion seleccion = (Configuracion) jComboBoxConfiguraciones.getSelectedItem();
        if (seleccion != null) {
            log.info("ID: " + seleccion.getConfiguracion_id() + ", Proyecto: " + seleccion.getNombre_proyecto());

            if (seleccion.getConfiguracion_id() == null) {
                setearCampos();
            } else {
                jTextFieldProyecto.setText(seleccion.getNombre_proyecto());

                jTextFieldPom.setText(seleccion.getPomDir());
                jTextFieldBuild.setText(seleccion.getBuildDir());
                jTextFieldWar.setText(seleccion.getWarName());
                jTextFieldWildfly.setText(seleccion.getWildflyDeployDir());
                jTextFieldMaven.setText(seleccion.getMavenExecutable());

            }
        }
    }//GEN-LAST:event_jComboBoxConfiguracionesActionPerformed

    private void jButtonCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCerrarActionPerformed
        // TODO add your handling code here:
        dispose();
        PrincipalFrm frm = new PrincipalFrm();
        frm.setVisible(true);
        
    }//GEN-LAST:event_jButtonCerrarActionPerformed

    private void setearCampos() {
        log.info("Setear Campos");
        jTextFieldProyecto.setText("");
        jTextFieldPom.setText("");
        jTextFieldBuild.setText("");
        jTextFieldWar.setText("");
        jTextFieldWildfly.setText("");
        jTextFieldMaven.setText("");

    }

    private void actualizarLista() {
        log.info("Actualizar la lista de configuracion");
        // Crear lista de configuaraciones
        ConfiguracionDAO cDao = new ConfiguracionDAO();
        try {
            List<Configuracion> lista = cDao.listarTodas();

            log.info("Cantiad de Configuraciones " + lista.size());

            jComboBoxConfiguraciones.removeAllItems();

            jComboBoxConfiguraciones.addItem(Configuracion.builder().nombre_proyecto("Nuevo").build());

            lista.forEach(item -> {
                jComboBoxConfiguraciones.addItem(item);
            });

        } catch (Exception ex) {
            ex.printStackTrace();
            log.info("Error buscar lista de configuarciones. " + ex);
            JOptionPane.showMessageDialog(null, "Error buscar lista de configuarciones. " + ex,
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EjecutarFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EjecutarFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EjecutarFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EjecutarFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EjecutarFrm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCerrar;
    private javax.swing.JButton jButtonProcesar;
    private javax.swing.JComboBox<Configuracion> jComboBoxConfiguraciones;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextFieldBuild;
    private javax.swing.JTextField jTextFieldMaven;
    private javax.swing.JTextField jTextFieldPom;
    private javax.swing.JTextField jTextFieldProyecto;
    private javax.swing.JTextField jTextFieldWar;
    private javax.swing.JTextField jTextFieldWildfly;
    // End of variables declaration//GEN-END:variables
}
